import sqlite3
import tkinter as tk
from tkinter import END,ttk,messagebox

def ekle():
    baglanti=sqlite3.connect("kütüphane.db")
    cursor=baglanti.cursor()
    cursor.execute("Insert into kitaplar('isim','yazar','yayınevi','tür','baskı') values (?,?,?,?,?)",(isim.get(),yazar.get(),yayınevi.get(),tür.get(),baskı.get()))
    baglanti.commit()
    isim.delete(0,END)
    yazar.delete(0,END)
    yayınevi.delete(0,END)
    tür.delete(0,END)
    baskı.delete(0,END)
    messagebox.showinfo("Bilgi","Kayıt Girildi")
def sil():
    baglanti=sqlite3.connect("kütüphane.db")
    cursor=baglanti.cursor()
    cursor.execute("Delete from kitaplar where isim=?",(isim.get()))
    baglanti.commit()
    isim.delete(0,END)
    yazar.delete(0,END)
    yayınevi.delete(0,END)
    tür.delete(0,END)
    baskı.delete(0,END)
    messagebox.showinfo("Bilgi","Kayıt Silindi")
def bul():
    try:
        pencere2=tk.Toplevel()
        tablo=ttk.Treeview(pencere2)
        tablo["columns"]=("A","B","C","D","E")
        tablo.column("#0",width="100")
        tablo.column("A",width="200")
        tablo.column("B",width="200")
        tablo.column("C",width="200")
        tablo.column("D",width="200")
        tablo.column("E",width="200")
        tablo.heading("#0",text="id")
        tablo.heading("A",text="Kitabın Adı")
        tablo.heading("B",text="Yazarın Adı")
        tablo.heading("C",text="Yayınevi Adı")
        tablo.heading("D",text="Kitabın Türü")
        tablo.heading("E",text="Baskı Sayısı")
        baglanti=sqlite3.connect("kütüphane.db")
        cursor=baglanti.cursor()
        cursor.execute("Select * from kitaplar where isim=? or yazar=? or yayınevi=? or tür=? or baskı=?",(isim.get(),yazar.get(),yayınevi.get(),tür.get(),baskı.get()))
        veriler=cursor.fetchall()
        for i in range(0,len(veriler)):
            tablo.insert('',"end",text=veriler[i][0],values=(veriler[i][1],veriler[i][2],veriler[i][3],veriler[i][4],veriler[i][5]))
            tablo.pack()
    except:
        pencere2.destroy()
        messagebox.showinfo("Kayıt Bulunamadı","Doğru Giriş Yaptığınızdan Eminolun")
        isim.delete(0,END)
        yazar.delete(0,END)
        yayınevi.delete(0,END)
        tür.delete(0,END)
        baskı.delete(0,END)

pencere=tk.Tk()
pencere.title("Kütüphanem V1.0")
pencere.geometry("300x400+300+150")
isim_label=tk.Label(pencere,text="Kitap İsmi:")
isim=tk.Entry(pencere)
yazar_label=tk.Label(pencere,text="Yazar Adı:")
yazar=tk.Entry(pencere)
yayınevi_label=tk.Label(pencere,text="Yayınevi ismi:")
yayınevi=tk.Entry(pencere)
tür_label=tk.Label(pencere,text="Kitabın Türü:")
tür=tk.Entry(pencere)
baskı_label=tk.Label(pencere,text="Kaçıncı Baskı:")
baskı=tk.Entry(pencere)
isim_label.place(x=10,y=30)
isim.place(x=100,y=30)
yazar_label.place(x=10,y=60)
yazar.place(x=100,y=60)
yayınevi_label.place(x=10,y=90)
yayınevi.place(x=100,y=90)
tür_label.place(x=10,y=120)
tür.place(x=100,y=120)
baskı_label.place(x=10,y=150)
baskı.place(x=100,y=150)
ekle_btn=tk.Button(pencere,text="Ekle",width=38,command=ekle)
bul_btn=tk.Button(pencere,text="Ara",width=38,command=bul)
sil_btn=tk.Button(pencere,text="Sil",width=38)
ekle_btn.place(x=10,y=190)
bul_btn.place(x=10,y=220)
sil_btn.place(x=10,y=250)



pencere.mainloop()
